### ISSUE TITLE
Host key verification fails with multiple uses in same job

### ISSUE THREAD

**Issue by PedrelliMath** [cssnr/stack-deploy-action#31]
### Issue Description

When using the same job to deploy to multiple environments, the job fails with the following error:

"Host key verification failed."

I worked around this issue by splitting the deployment into separate jobs for each environment.

### Log Output

```shell
error during connect: Get "http://docker.example.com/v1.49/info": command [ssh -o ConnectTimeout=30 -T -l *** -p *** -- *** docker system dial-stdio] has exited with exit status 255, make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=Host key verification failed.
```

**Comment by smashedr** [comment]
That sounds like a bug I would like to get fixed!

If the repository is public, it would be very helpful to get a link to the action logs...

The test does a double deployment in a single job, however; to the same host with the same key. I will have to add another environment to the test harness just to attempt to reproduce the issue. Thank you very much for raising this issue, but I may need a few days to setup a reproduction.

**Comment by PedrelliMath** [comment]
In my case, its diferent hosts and diferent keys.

**Comment by smashedr** [comment]
Just a quick update; I did a test locally but was **not** able to reproduce the issue. I would have expected this to reproduce the issue.

This test deployed to 2 different hosts, with 2 different users and 2 different SSH keys in a single job.
Test run logs: [log.txt](https://github.com/user-attachments/files/20219998/log.txt)

```yaml
- name: "1: Write YAML"
  if: ${{ !cancelled() }}
  uses: teunmooij/yaml@v1
  with:
    to-file: "docker-compose.yaml"
    data: |
      {"version":"3.8","services":{"alpine":{"image":"alpine:latest","command":"tail -f /dev/null"}}}

- name: "1: Test Host 1"
  if: ${{ !cancelled() }}
  uses: ./
  with:
    name: test_stack-deploy
    file: docker-compose.yaml
    host: ${{ secrets.DOCKER_HOST }}
    port: ${{ secrets.DOCKER_PORT }}
    user: ${{ secrets.DOCKER_USER }}
    ssh_key: ${{ secrets.DOCKER_SSH_KEY }}
    detach: true
    summary: false

- name: "2: Write YAML"
  if: ${{ !cancelled() && !github.event.act }}
  uses: teunmooij/yaml@v1
  with:
    to-file: "docker-compose.yaml"
    data: |
      {"version":"3.8","services":{"alpine":{"image":"alpine:latest","command":"tail -f /dev/null"}}}

- name: "2: Test Host 2"
  if: ${{ !cancelled() && !github.event.act }}
  uses: ./
  with:
    name: test_stack-deploy
    file: docker-compose.yaml
    host: ${{ secrets.DOCKER_HOST2 }}
    port: ${{ secrets.DOCKER_PORT }}
    user: ${{ secrets.DOCKER_USER2 }}
    ssh_key: ${{ secrets.DOCKER_SSH_KEY2 }}
    mode: compose
    summary: false
```

I can't imagine what could be different in the github actions environment. But when I get some spare time over the weekend I can setup another environment for testing from github actions and add some more secrets. 

In the mean time, I would be glad to review your logs, just make sure there is NO SENSITIVE information in them. You can view the raw logs from the steps below:

![Image](https://github.com/user-attachments/assets/8268e5fc-e969-4469-abe6-96a62d62b15b)
